// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALmZSVzbdRBiiPPmJgHO8NyYx7iwaXQVI',
    appId: '1:954165232602:web:5a4d664cc6790d2a58f6e3',
    messagingSenderId: '954165232602',
    projectId: 'streamsync-51abd',
    authDomain: 'streamsync-51abd.firebaseapp.com',
    databaseURL: 'https://streamsync-51abd-default-rtdb.firebaseio.com',
    storageBucket: 'streamsync-51abd.firebasestorage.app',
    measurementId: 'G-L32VQW3HCR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbJHWWyr4Vw9fjqwjQnOyOINitnQaYo20',
    appId: '1:954165232602:android:6554c2eb1b929b4f58f6e3',
    messagingSenderId: '954165232602',
    projectId: 'streamsync-51abd',
    databaseURL: 'https://streamsync-51abd-default-rtdb.firebaseio.com',
    storageBucket: 'streamsync-51abd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIM59ouv83y7pAjs6lD1zlFWlaWP6wIFc',
    appId: '1:954165232602:ios:58cae46750a15e6758f6e3',
    messagingSenderId: '954165232602',
    projectId: 'streamsync-51abd',
    databaseURL: 'https://streamsync-51abd-default-rtdb.firebaseio.com',
    storageBucket: 'streamsync-51abd.firebasestorage.app',
    iosClientId: '954165232602-kmp0st8u27qg4opnc3au26e36bnuagu4.apps.googleusercontent.com',
    iosBundleId: 'com.example.streamsynx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIM59ouv83y7pAjs6lD1zlFWlaWP6wIFc',
    appId: '1:954165232602:ios:58cae46750a15e6758f6e3',
    messagingSenderId: '954165232602',
    projectId: 'streamsync-51abd',
    databaseURL: 'https://streamsync-51abd-default-rtdb.firebaseio.com',
    storageBucket: 'streamsync-51abd.firebasestorage.app',
    iosClientId: '954165232602-kmp0st8u27qg4opnc3au26e36bnuagu4.apps.googleusercontent.com',
    iosBundleId: 'com.example.streamsynx',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALmZSVzbdRBiiPPmJgHO8NyYx7iwaXQVI',
    appId: '1:954165232602:web:848d673239a51b9358f6e3',
    messagingSenderId: '954165232602',
    projectId: 'streamsync-51abd',
    authDomain: 'streamsync-51abd.firebaseapp.com',
    databaseURL: 'https://streamsync-51abd-default-rtdb.firebaseio.com',
    storageBucket: 'streamsync-51abd.firebasestorage.app',
    measurementId: 'G-M316W4KS1P',
  );
}
